vieritystä
finnishtransportagency/harja pull request #2035
Opened 2020-12-28 08:50 UTC by jlansineva

2021-03-01 13:26 UTC, petar-jr requested changes
Pitäisikö olla ainakin backend ja non-UI juttuille automaatisoitu testi?

2021-03-02 07:09 UTC, maaritlaine commented on tietokanta/src/main/resources/db/migration/V1_864__.sql
> +create table suunnittelu_kustannussuunnitelman_tila (
Riittäiskö taulun nimeksi kustannussuunnitelman_tila?
(Ite en tykkää sijamuotojen käytöstä taulujen nimissä, mutta niitä on Harjassa muutkin harrastaneet, joten kaikki ei selvästikään oo mun kannalla.)

2021-03-02 07:11 UTC, maaritlaine commented on tietokanta/src/main/resources/db/migration/V1_864__.sql
> +create type suunnittelu_kategoriat as enum ('hankintakustannukset', 'erillishankinnat', 'johto-ja-hallintokorvaus', 'hoidonjohtopalkkio', 'tavoite-ja-kattohinta', 'tilaajan-vararahastot');
Kyse on osista eikä kategorioista. kustannusuunnitelma_osat tai kustannussuunnitelman_osat?
Myös tilaajan-rahavaraukset ei tilaajan-vararahastot.

2021-03-02 07:13 UTC, maaritlaine commented on tietokanta/src/main/resources/db/migration/V1_864__.sql
> +vahvistaja integer references kayttaja(id),
Tarvitaanko vahvistaja erikseen? Muokkautuuko tieto muuten kuin vahvistamalla? Eikö luoja ja muokkaaja oo vahvistajia?

2021-07-08 07:50 UTC, closed without merging