Checkbox tyylimuutokset
finnishtransportagency/harja pull request #2120
Opened 2021-05-07 12:15 UTC by jpluomajoki-solita

2021-05-10 04:47 UTC, rckopteri commented
Testatessa tuli raportteja värkätessä tällainen virhe:
loki.cljs:20 VIRHE RENDERÖITÄESSÄ KOMPONENTTIA!
Error: Assert failed: Jos checkboxin datan tyyppi on boolean atomin sijasta, valitse! pitää olla funktio
    at kentat.cljs:527

2021-05-10 04:51 UTC, rckopteri commented
Editoitavissa taulukoissa esim. yleiset sivulla checkboxi on taulukkorivillä väärässä paikassa, koska label elementillä on margin-top: 1rem. Se on varmaan muualla ok, mutta ei gridissä.

2021-05-10 04:54 UTC, rckopteri commented
Aikataulu sivulla on sama virhe ja koko homma räsähtää
Error: Assert failed: Jos checkboxin datan tyyppi on boolean atomin sijasta, valitse! pitää olla funktio
    at kentat.cljs:527

2021-05-10 04:55 UTC, rckopteri commented
Paikkauskohteissa filttereissä olevat checkboxit on menneet aivan sekaisin.

2021-05-10 04:55 UTC, rckopteri requested changes

2021-05-10 04:55 UTC, rckopteri commented on src/cljs/harja/ui/kentat.cljs
> +            [reagent.ratom :as ratom]
reagent.core.atom ja reagent.ratom taitaa olla sama asia: 
http://reagent-project.github.io/docs/master/reagent.ratom.html
http://reagent-project.github.io/docs/master/reagent.core.html

2021-05-10 04:55 UTC, rckopteri commented on dev-resources/less/yleiset.less
> +/*
👍

2021-05-10 06:47 UTC, jpluomajoki-solita commented on src/cljs/harja/ui/kentat.cljs
> +            [reagent.ratom :as ratom]
Jos nyt oikein ymmärrän, niin ei ole. reagent.core/atom on funktio, joka luo atomin, ja tässä käytetään reagent.ratom/Ratom, joka puolestaan on luokka. Sitä käytetään tarkastamaan, että onko checkboxille annettu arvo atomi tai wrap, vai boolean, jolloinka checkboxille pitäisi antaa myös valitse!-funktio, koska immutability jne.

2021-05-10 11:01 UTC, jpluomajoki-solita commented
Korjattu seuraavat:
 - Korjattu virheilmoitukset puuttuvista funktioista
 - marginit gridissä
 - Paikkauskohteiden filtterit

2021-05-10 12:35 UTC, rckopteri commented
Paikkauskohteiden filttereissä vielä turhaa marginia labelissa.
Sorry. My bad. Jostain syystä ei ollutkaan ympäristö täysin fressi, kun aloin testaamaan. On se kunnossa.
👍

2021-05-10 12:40 UTC, rckopteri commented
Aikataulu -välilehdellä rivittyy vähän hassusti ne aiemmin hajonneet checkboxit. Siellä on 150px levynen kenttä, joka ei riitä tuon tekstin kanssa enää.

2021-05-10 13:33 UTC, jpluomajoki-solita commented
Levennetty aikataulujen kenttää, jotta checkboxit mahtuvat paremmin.

2021-05-11 04:26 UTC, rckopteri approved these changes

2021-05-11 12:31 UTC, merged