Rest Api sahkoposti
finnishtransportagency/harja pull request #2392
Opened 2022-02-23 08:41 UTC by rckopteri

2022-03-03 09:50 UTC, sirkkalap requested changes
Pyydän muutoksia :)

2022-03-03 09:50 UTC, sirkkalap commented on src/clj/harja/palvelin/integraatiot/vayla_rest/sahkoposti.clj
> +    ;; Ei tee tarkoituksellisesti mitään, mutta toteuttaa Protokollan
Voisi lokittaa, jos joku sattuu tätä kutsumaan.

2022-03-03 09:50 UTC, sirkkalap commented on src/clj/harja/palvelin/integraatiot/vayla_rest/sahkoposti.clj
> +        (kutsukasittely/kasittele-kutsu db integraatioloki :sahkoposti-vastaanotto
Käyttäjätarkistus voisi kannattaa tehdä mahdollisimman aikaisin. Jos käyttäjä ei täsmää Digian tunnuksen kanssa, ei edes validoida viestiä, vaan pudotetaan hanskat.

2022-03-03 09:50 UTC, sirkkalap commented on src/clj/harja/palvelin/integraatiot/vayla_rest/sahkoposti.clj
> +  (let [#_ (log/debug "Sähköpostivastauksen body:" (pr-str body))]
Poistllaan

2022-03-03 09:50 UTC, sirkkalap commented on src/clj/harja/palvelin/integraatiot/vayla_rest/sahkoposti.clj
> +(defn kasittele-sahkoposti-vastaus
Onko tälle mitään käyttöä? Ei poikkeuskäsittelyä, ei lokitusta eikä mitään kirjoiteta tietokantaan.

2022-03-03 09:50 UTC, sirkkalap commented on test/clj/harja/palvelin/integraatiot/vayla_rest/sahkoposti_api_test.clj
> +
Entäs, jos Bobby Tables: https://portswigger.net/web-security/xxe

2022-03-03 09:50 UTC, sirkkalap commented on test/clj/harja/palvelin/integraatiot/vayla_rest/sahkoposti_api_test.clj
> +                          (sahkoposti/laheta-viesti! (:api-sahkoposti jarjestelma)
Tässä pitäisi olla failava http-palvelu

2022-03-03 09:50 UTC, sirkkalap commented on test/clj/harja/palvelin/integraatiot/vayla_rest/sahkoposti_api_test.clj
> +;; Simuloi tilannetta, jossa sähköpostipalvelin ei vastaa
Voisi olla testi myös sille, kun lähettettävän postin restipalvelu ei vastaa

2022-03-03 09:53 UTC, rckopteri commented on src/clj/harja/palvelin/integraatiot/vayla_rest/sahkoposti.clj
> +    ;; Ei tee tarkoituksellisesti mitään, mutta toteuttaa Protokollan
Logitus lisätty

2022-03-03 09:54 UTC, rckopteri commented on src/clj/harja/palvelin/integraatiot/vayla_rest/sahkoposti.clj
> +        (kutsukasittely/kasittele-kutsu db integraatioloki :sahkoposti-vastaanotto
Tarkistelin tämän toiminnan. Se toimii kuten kaikki muutkin api rajapinnat, jotka Harjaan on toteutettu. Otamme kuitenkin keskusteluun, että tarvitseeko tähän tehdä jotain muuta.
Noita muita rajapintoja nimittäin voi kutsua Digian lisäksi myös urakoitsijat, jotka taas eivät saa kutsua tätä rajapintaa.

2022-03-03 09:54 UTC, rckopteri commented on src/clj/harja/palvelin/integraatiot/vayla_rest/sahkoposti.clj
> +  (let [#_ (log/debug "Sähköpostivastauksen body:" (pr-str body))]
Poistettu

2022-03-03 10:11 UTC, rckopteri commented on src/clj/harja/palvelin/integraatiot/vayla_rest/sahkoposti.clj
> +(defn kasittele-sahkoposti-vastaus
Tein tälle käsittelyn ylemmäksi eli integraatiotapahtuman käsittelyyn. Se tuntui oikeammalta paikalta.
Eli jos vastauspää ilmoittaa virheestä, niin se logitetaan tietokantaan kutsuttaessa, sitä ei välitetä enää tänne.

Mutta lisäsin myös tuohon selityksiä, että virheen sattuessa palauttaa nil, jonka tätä kutsuva funktio osaa taas käsitellä oikein.

2022-03-03 10:56 UTC, rckopteri commented on test/clj/harja/palvelin/integraatiot/vayla_rest/sahkoposti_api_test.clj
> +                          (sahkoposti/laheta-viesti! (:api-sahkoposti jarjestelma)
Korjattu

2022-03-03 10:56 UTC, rckopteri commented on test/clj/harja/palvelin/integraatiot/vayla_rest/sahkoposti_api_test.clj
> +;; Simuloi tilannetta, jossa sähköpostipalvelin ei vastaa
Lisätty

2022-03-14 06:02 UTC, rckopteri commented on test/clj/harja/palvelin/integraatiot/vayla_rest/sahkoposti_api_test.clj
> +
Tein testejä, joissa koitetaan lisätä xml:ään jotain väärää. Riittäiskö tuo?

2022-03-14 08:43 UTC, sirkkalap commented on test/clj/harja/palvelin/integraatiot/vayla_rest/sahkoposti_api_test.clj
> +
Tuo on aika advanced hyökkäys. Ehkä olemme tyytyväisiä nykytilaan.

2022-03-14 08:44 UTC, sirkkalap approved these changes

2022-03-14 13:17 UTC, merged