VHAR-5664 Tee ajastettu tehtävä joka hakee öisin uudet varusteet Velhosta
finnishtransportagency/harja pull request #2553
Opened 2022-08-04 07:47 UTC by sirkkalap

2022-08-04 09:45 UTC, sirkkalap commented on asetukset.edn
> +         :varuste-haku-suoritusaika [13 26 00]
00 ei ole 0

2022-08-04 09:45 UTC, sirkkalap commented on src/clj/harja/palvelin/integraatiot/velho/velho_komponentti.clj
> +            [harja.palvelin.tyokalut.ajastettu-tehtava :as ajastettu-tehtava]
Laitetaan vielä järjestykseen. Ulkoiset importit ensin.

2022-08-04 09:45 UTC, sirkkalap commented on src/clj/harja/palvelin/integraatiot/velho/velho_komponentti.clj
> +    (fn [_])))
Constantly nil

2022-08-04 09:45 UTC, sirkkalap commented on src/clj/harja/palvelin/integraatiot/velho/velho_komponentti.clj
> +    "varustetoteuma-haku"
Laitetaan funktion nimi tähän nimeksi

2022-08-04 10:53 UTC, jpluomajoki-solita commented on src/clj/harja/palvelin/integraatiot/velho/velho_komponentti.clj
> +            [harja.tyokalut.yleiset :as yleiset]
käyttämätön require

2022-08-04 10:53 UTC, jpluomajoki-solita commented on src/clj/harja/palvelin/integraatiot/velho/velho_komponentti.clj
> +    (let [suoritusaika  (:varuste-haku-suoritusaika asetukset)]
kaksi välimerkkiä

2022-08-04 10:53 UTC, jpluomajoki-solita commented on src/clj/harja/palvelin/integraatiot/velho/velho_komponentti.clj
> +    (fn [_])))
Tämä pitää olla 0-arity, koska ajasta-paivittain palauttaa 0-arity funktion, jota kutsutaan stopissa.

2022-08-04 10:53 UTC, jpluomajoki-solita commented on src/clj/harja/palvelin/integraatiot/velho/velho_komponentti.clj
> +    (:varustetoteuma-haku-tehtava this)
Tätä funktiota pitäisi myös kutsua. Mallina käytetyssä sähke-komponentissa on ilmeisesti myös käytetty tätä väärin. Muissa vastaavanlaisissa tätä käytetään eri tavalla, katso esim. sampo-komponentti

2022-08-04 11:05 UTC, sirkkalap reviewed
Muutokset toteutettu

2022-08-04 11:12 UTC, sirkkalap commented on src/clj/harja/palvelin/integraatiot/velho/velho_komponentti.clj
> +    (:varustetoteuma-haku-tehtava this)
Tuolla näyttäisi olevan myös tehty ne dissoc:t noille oikein.

2022-08-04 11:25 UTC, jpluomajoki-solita approved these changes

2022-08-04 11:35 UTC, jpluomajoki-solita requested changes
Otetaanpa approve vielä pois, testit näköjään räjähti tämän komponentin takia

2022-08-04 12:05 UTC, jpluomajoki-solita commented on src/clj/harja/palvelin/integraatiot/velho/velho_komponentti.clj
> +    this)
Tässä on ylimääräinen `this`, joka aiheuttaa sen, ettei `:varustetoteuma-tuonti-tehtava` tallennu komponenttiin.

2022-08-04 12:21 UTC, jpluomajoki-solita approved these changes
LGTM jos testit menee läpi

2022-08-04 12:26 UTC, jarnovayrynen approved these changes
Ok, mutta ennen mergeä on syytä päivittää asetukset.edn filut eri ympäristöille harja-ci projektissa.

2022-08-05 07:25 UTC, merged

2022-08-05 09:53 UTC, sirkkalap commented
> 



> Ok, mutta ennen mergeä on syytä päivittää asetukset.edn filut eri ympäristöille harja-ci projektissa.

Ei tarvetta. Parametri joka lisättiin on optionaalinen ja sen puuttuminen on toteutettu jättämällä ajo suorittamatta.