Vhar 7421 analytiikkasql
finnishtransportagency/harja pull request #2794
Opened 2023-03-10 19:47 UTC by solita-staskila

2023-03-13 05:44 UTC, rckopteri commented on tietokanta/src/main/resources/db/migration/V1_948__.sql
> +               t.luotu                                                                    as toteuma_luotu,
Vanhoihin migraatiotiedostoihin ei voi tehdä muutoksia.

2023-03-13 05:58 UTC, solita-staskila commented on tietokanta/src/main/resources/db/migration/V1_948__.sql
> +               t.luotu                                                                    as toteuma_luotu,
Commit otettu takaisin

2023-03-13 05:58 UTC, rckopteri approved these changes

2023-03-13 08:39 UTC, maaritlaine reviewed
SQL on muutettu juuri kuten tarvitsikin, mutta tuli nyt sitten mieleen, että kun SQL nimeltä **hae-reittitoteumat-analytiikalle** hakee aikaleimojen perusteella rivit analytiikka_toteumat-taulusta, niin siellähän pitäisi myös olla hyödynnettävissä toteuma_materiaali-taulun luonti- ja muokkausaika. 

Kaivataan siis vielä iterointikierros, jolla lisätään sarakkeet analytiikka_toteumat-tauluun ja päivitetään tuon SQL:n hakuehtoa.

2023-03-14 08:49 UTC, rckopteri commented on src/clj/harja/kyselyt/toteumat.sql
> +OR ((t.toteuma_materiaali_muokattu IS NOT NULL AND t.toteuma_materiaali_muokattu BETWEEN :alkuaika::TIMESTAMP AND :loppuaika::TIMESTAMP)
Jotenkin ensimmäisellä katselmointikierroksella tämän sivuutin.
Minkä verran tämä hidastaa hakua? 
Tältä ainakin puuttuu indeksi, joten oletuksena haku menee todella hitaaksi.

2023-03-14 08:49 UTC, rckopteri commented on tietokanta/src/main/resources/db/migration/V1_997__.sql
> +ALTER TABLE analytiikka_toteumat ADD COLUMN toteuma_materiaali_luotu timestamp;
Lisää indeksit molemmille.

2023-03-14 08:50 UTC, rckopteri requested changes
Jätin pari kommenttia suorituskyvystä

2023-03-14 10:27 UTC, solita-staskila commented on src/clj/harja/kyselyt/toteumat.sql
> +OR ((t.toteuma_materiaali_muokattu IS NOT NULL AND t.toteuma_materiaali_muokattu BETWEEN :alkuaika::TIMESTAMP AND :loppuaika::TIMESTAMP)
nämä rivit tuli vasta sinun katselmoinnin jälkeen, ja hyvä pointti.
lisään noille samanlaisen indeksin mitä noille **_toteuma_muutostiedot_muokattu_** on tehty. 

voin kokeilla vielä singletonilla että sieltä tulee vastaus.

2023-03-16 09:33 UTC, rckopteri approved these changes

2023-03-16 09:57 UTC, maaritlaine approved these changes

2023-03-16 13:00 UTC, merged