Vhar 7805 hairioilmoitus
finnishtransportagency/harja pull request #3001
Opened 2023-08-15 07:12 UTC by pohjamat

2023-08-15 10:22 UTC, solita-staskila requested changes
Hieman pilkun viilauksia koodista

2023-08-15 10:22 UTC, solita-staskila commented on src/clj/harja/palvelin/palvelut/hairioilmoitukset.clj
> +     }))
Korjaa roikkuvat sulkeet ylemmälle riville

2023-08-15 10:22 UTC, solita-staskila commented on src/clj/harja/palvelin/palvelut/hairioilmoitukset.clj
> +    ))
Korjaa roikkuvat sulkeet

2023-08-15 10:22 UTC, solita-staskila commented on src/cljc/harja/domain/hairioilmoitus.cljc
> +      )
Korjaa roikkuvat sulkeet

2023-08-15 10:22 UTC, solita-staskila commented on src/cljc/harja/domain/hairioilmoitus.cljc
> +      )
Korjaa roikkuvat sulkeet

2023-08-15 10:22 UTC, solita-staskila commented on src/cljc/harja/domain/hairioilmoitus.cljc
> +             )))
Korjaa roikkuvat sulkeet

2023-08-15 10:22 UTC, solita-staskila commented on src/cljc/harja/domain/hairioilmoitus.cljc
> +  )
Korjaa roikkuvat sulkeet + turha kommentti

2023-08-15 10:22 UTC, solita-staskila commented on src/cljc/harja/domain/hairioilmoitus.cljc
> +
Vähän nillitystä mutta täällä on turhaa väliä tiedoston lopussa, yksi tyhjä rivi on riittävä koska siitä jotkin IDEAt valittaa

2023-08-15 10:22 UTC, solita-staskila commented on src/cljs/harja/tiedot/hallinta/hairiot.cljs
> +          (do
Turha (do), (do) voi käyttää esim jos tarvitaan tehdä iffin sisälle enemmän kuin 1 rivi koodia, tässä sellaista tilannetta ei ole

2023-08-15 10:22 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/hairiot.cljs
> +        ]
Korjaa roikkuvat sulkeet, -> 
[tulevat (hairio/tulevat-hairiot hairiot)]

2023-08-15 10:22 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/hairiot.cljs
> +              ]]])])]))
Korjaa roikkuvat sulkeet, + onko tässä oikea formatointi?

2023-08-15 10:22 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/hairiot.cljs
> +            ]
Korjaa roikkuvat sulkeet

2023-08-15 10:22 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/hairiot.cljs
> +                                  }]
Korjaa roikkuvat sulkeet

2023-08-15 10:22 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/hairiot.cljs
> +           ])))))
Korjaa roikkuvat sulkeet

2023-08-15 10:22 UTC, solita-staskila commented on test/clj/harja/palvelin/palvelut/hairioilmoitukset_test.clj
> +          ]
Korjaa roikkuvat sulkeet

2023-08-15 10:22 UTC, solita-staskila commented on test/cljc/harja/domain/hairioilmoitus_test.cljc
> +    )
Korjaa roikkuvia sulkeita koko funktiosta , turhat kommentit voi poistaa

2023-08-15 10:22 UTC, solita-staskila commented on test/cljc/harja/domain/hairioilmoitus_test.cljc
> +    (is (hairio/onko-paallekkainen (pvm/dateksi (pvm/pvm-plus-tuntia (pvm/nyt) 2)) (pvm/dateksi (pvm/pvm-plus-tuntia (pvm/nyt) 4)) vanhat))))
Koko tiedostossa on roikkuvia sulkeita, näin ei clojuressa ruukata tehdä

2023-08-15 11:09 UTC, pohjamat commented on src/clj/harja/palvelin/palvelut/hairioilmoitukset.clj
> +     }))
ok

2023-08-15 11:09 UTC, pohjamat commented on src/clj/harja/palvelin/palvelut/hairioilmoitukset.clj
> +    ))
ok

2023-08-15 11:11 UTC, pohjamat commented on src/cljc/harja/domain/hairioilmoitus.cljc
> +
ok

2023-08-15 11:18 UTC, pohjamat commented on src/cljc/harja/domain/hairioilmoitus.cljc
> +  )
tässä oli jätetty kommentin taakse logiikka mikä toimii niin että jos aikaväli jatkuu suoraan siitä mihin edellinen päättyy, ei sallita. Arvelin että pitäisi toimia niin voi laittaa jatkumaan suoraan ilman että pitää jättää vaikka minuutti väliä.
Ehkä kommentin voi poistaa. Ja roikkuvat sulkeet ainakin.

2023-08-15 11:23 UTC, pohjamat commented on src/cljc/harja/domain/hairioilmoitus.cljc
> +             )))
tässä pitäisi varmaan nekin tapaukset että vanhassa on jompi kumpi avoin, ja että uudessa on myös avoin puoli.
Tässä voisi myös harkita pitäisikö tämä logiikka laittaa pvm namespaceen.

2023-08-15 11:24 UTC, pohjamat commented on src/cljc/harja/domain/hairioilmoitus.cljc
> +      )
ok

2023-08-15 11:24 UTC, pohjamat commented on src/cljc/harja/domain/hairioilmoitus.cljc
> +      )
ok

2023-08-15 11:34 UTC, pohjamat commented on src/cljs/harja/views/hallinta/hairiot.cljs
> +           ])))))
ok

2023-08-15 11:35 UTC, pohjamat commented on src/cljs/harja/views/hallinta/hairiot.cljs
> +                                  }]
ok

2023-08-15 11:36 UTC, pohjamat commented on src/cljs/harja/views/hallinta/hairiot.cljs
> +            ]
ok

2023-08-15 11:37 UTC, pohjamat commented on src/cljs/harja/views/hallinta/hairiot.cljs
> +              ]]])])]))
ok, vähän muuttui formatointi

2023-08-15 11:39 UTC, pohjamat commented on src/cljs/harja/views/hallinta/hairiot.cljs
> +        ]
ok

2023-08-15 11:41 UTC, pohjamat commented on src/cljs/harja/tiedot/hallinta/hairiot.cljs
> +          (do
ok

2023-08-15 11:43 UTC, pohjamat commented on test/clj/harja/palvelin/palvelut/hairioilmoitukset_test.clj
> +          ]
ok

2023-08-15 12:40 UTC, solita-staskila commented
Jos häiriötilanteen alku ja loppuaika ovat joko samoja, tai loppuaika on ennen alkuaikaa, palvelin heittää pahan näköisen constraint check virheen. Voisko tuon vielä korjata ja näyttää käyttäjälle tästä vielä viesti että aikaväli ei ole validi?

2023-08-15 12:45 UTC, pohjamat commented
joo, noita validointeja ei ole tehty ennen kuin vasta kun tietokanta tekee. Laitetaan tuollaiset validoinnit mukaan.

2023-08-21 07:42 UTC, solita-staskila approved these changes
Näyttää jo ihan hyvältä. Pari siistimis ehdotusta vielä.

2023-08-21 07:42 UTC, solita-staskila commented on src/clj/harja/palvelin/palvelut/hairioilmoitukset.clj
> +(defn- validoi-ajat [db alkuaika loppuaika]
Tässä hiukan epäselvän näköistä logiikkaa sekä yksi (if) ilman elseä. Tuo alku/loppuaikojen näyttö viesteissä tekee viestistä käyttäjälle myös vähän sekavan näköisen, tämän voisi tehdä selkeämmin. Esimerkiksi :
```
(defn- validoi-ajat [db alkuaika loppuaika]
  (let [vanhat (specql/fetch db ::hairio/hairioilmoitus
                 hairio/sarakkeet
                 {::hairio/voimassa? true})]
    (cond
      (= loppuaika alkuaika)
      [{:virhe (str "Alkuaika ja loppuaika eivät voi olla samat.")}]

      (pvm/ennen? loppuaika alkuaika)
      [{:virhe (str "Alkuajan pitäisi olla ennen loppuaikaa.")}]

      (hairio/onko-paallekkainen alkuaika loppuaika vanhat)
      [{:virhe (str "Aikaväli leikkaa olemassaolevaa häiriöilmoitusta.")}]
      ;; Ei virheitä
      :else nil)))
``` 


Erota erilliset funktiot myös tyhjällä rivillä, eli tuo alempi funktio

2023-08-21 07:42 UTC, solita-staskila commented on src/clj/harja/palvelin/palvelut/hairioilmoitukset.clj
> +  (aseta-vanhat-hairioilmoitukset-pois db) ; TODO: onko hyvä paikka tehdä tämä?
Tämä on OK, kommentin voi poistaa

2023-08-21 07:42 UTC, solita-staskila commented on src/cljc/harja/domain/hairioilmoitus.cljc
> +(defn onko-paallekkainen [uusialku uusiloppu vanhat]
Tässäkin voisi lyödä yhden tyhjän rivin funktioiden väliin

2023-08-21 07:42 UTC, solita-staskila commented on src/cljs/harja/tiedot/hallinta/hairiot.cljs
>                                                          ::hairio/loppuaika loppuaika}))]
Tämän tiedoston ekalla rivillä tosi paljon turhia requireja, vaikka ei tässä pullarissa ole tehty, ne voisi silti siivota. Luulen että tässä kaikki mitä tarvitaan:

```
(ns harja.tiedot.hallinta.hairiot
  (:require [reagent.core :refer [atom] :as r]
            [cljs.core.async :refer [<!]]
            [harja.domain.hairioilmoitus :as hairio]
            [harja.tiedot.hairioilmoitukset :as hairio-ui]
            [harja.asiakas.kommunikaatio :as k]
            [harja.ui.viesti :as viesti])
  (:require-macros [cljs.core.async.macros :refer [go]]))
```

2023-08-21 07:42 UTC, solita-staskila commented on src/cljs/harja/tiedot/hairioilmoitukset.cljs
>  (defn hae-tuorein-hairioilmoitus! []
Tässä tiedostossa sama homma, eli turhia requireja, voisi nämäkin siivota:

```
(ns harja.tiedot.hairioilmoitukset
  (:require [reagent.core :refer [atom]]
            [cljs.core.async :refer [<!]]
            [cljs.core.async :refer [<! timeout]]
            [harja.asiakas.kommunikaatio :as k])
  (:require-macros [cljs.core.async.macros :refer [go go-loop]]))
```

2023-08-21 07:53 UTC, solita-staskila commented on src/cljc/harja/domain/hairioilmoitus.cljc
> +  (some #(aikavalit-leikkaavat-sivuaminen-sallittu? (::alkuaika %) (::loppuaika %) uusialku uusiloppu) vanhat))
Tämä funktio palauttaa joko true tai nil -> 
Eli voisikohan tämän vielä wrappaa (boolean) sisälle ja laittaa funktion nimeen kysymysmerkki perään, tarkottaen että funktio palauttaa joko true tai false.

2023-08-21 12:34 UTC, pohjamat commented on src/cljc/harja/domain/hairioilmoitus.cljc
> +  (some #(aikavalit-leikkaavat-sivuaminen-sallittu? (::alkuaika %) (::loppuaika %) uusialku uusiloppu) vanhat))
ok

2023-08-21 12:36 UTC, pohjamat commented on src/cljc/harja/domain/hairioilmoitus.cljc
> +(defn onko-paallekkainen [uusialku uusiloppu vanhat]
ok

2023-08-21 12:36 UTC, pohjamat commented on src/clj/harja/palvelin/palvelut/hairioilmoitukset.clj
> +  (aseta-vanhat-hairioilmoitukset-pois db) ; TODO: onko hyvä paikka tehdä tämä?
ok

2023-08-21 12:40 UTC, pohjamat commented on src/clj/harja/palvelin/palvelut/hairioilmoitukset.clj
> +(defn- validoi-ajat [db alkuaika loppuaika]
eikös tuo 'vanhat' kannata inline, niin pääsee let osiosta eroon?

2023-08-21 12:42 UTC, solita-staskila commented on src/clj/harja/palvelin/palvelut/hairioilmoitukset.clj
> +(defn- validoi-ajat [db alkuaika loppuaika]
Ajattelin vaan että koodi voisi olla luettavampaa, mutta voit toki tehdä niinkin 👍

2023-08-21 13:10 UTC, pohjamat commented on src/cljs/harja/tiedot/hallinta/hairiot.cljs
>                                                          ::hairio/loppuaika loppuaika}))]
ok

2023-08-22 04:35 UTC, merged