VHAR-8020 Muuta tarkastus-taulun indeksi
finnishtransportagency/harja pull request #3021
Opened 2023-08-30 03:19 UTC by maaritlaine

2023-08-30 05:15 UTC, rckopteri commented on tietokanta/src/main/resources/db/migration/V1_1040__.sql
> +ALTER TABLE tarkastus
Tämä pitänee ajaa jokaiseen tarkastus partitioon tyyliin:
ALTER TABLE tarkastus_2015_q1
DROP CONSTRAINT tarkastus_ulkoinen_id_luoja_uniikki;

CREATE UNIQUE INDEX tarkastus_ulkoinen_id_urakka_uniikki ON tarkastus_2015_q1 (ulkoinen_id, urakka);

Ja tämä pitää testata singletonilla, koska on täysin mahdollista, että löytyy duplikaatteja.

2023-08-30 05:17 UTC, rckopteri commented on tietokanta/src/main/resources/db/migration/V1_1040__.sql
> +ALTER TABLE tarkastus
Katsopas 1029 sql tiedostoa. Tämä indeksi on tehty siellä.

2023-08-30 05:18 UTC, rckopteri requested changes
Indeksi on jo tehty.

2023-08-31 12:08 UTC, maaritlaine commented on tietokanta/src/main/resources/db/migration/V1_1040__.sql
> +ALTER TABLE tarkastus
Muutin indeksien päivitystä niin, että nyt lisätään siihen 2015-tauluun ja juuritauluun indeksi (ulkoinen id, urakka, tyyppi, poistettu), joka jo partitiotauluista löytyykin.

2023-09-01 04:25 UTC, rckopteri commented on src/clj/harja/kyselyt/tarkastukset.sql
> +WHERE urakka = :urakka AND id = :id and tyyppi = :tyyppi :: tarkastustyyppi;
Samalla id:llä ei varmaankaan ole yhtään tarkastusta. Eli minusta tässä tuo urakan lisäyskin on jo overkill.
Jättäisin siis tyylin myöskin pois hakuehdosta.

2023-09-01 04:26 UTC, rckopteri commented on src/clj/harja/kyselyt/tarkastukset.sql
> +WHERE urakka = :urakka - id
Koodin formatointi on rikkonut urakka-id parametrin

2023-09-01 04:28 UTC, rckopteri approved these changes
Jätin vielä muutaman huomion.
Niiden tsekkaamisen jälkeen voi mergettää.

2023-09-01 09:43 UTC, maaritlaine commented on src/clj/harja/kyselyt/tarkastukset.sql
> +WHERE urakka = :urakka AND id = :id and tyyppi = :tyyppi :: tarkastustyyppi;
Tää oli kesken. Tyyppi pitää tosiaan olla mukana vaan deletessä, koska tossa ei käytetä ulkoista id:tä. Urakkakin on varmaan lisätty joskus siksi, että on ajateltu id:n olevan ulkoinen.

2023-09-01 09:56 UTC, rckopteri approved these changes

2023-09-01 09:57 UTC, rckopteri approved these changes

2023-09-01 10:51 UTC, merged