Vhar 8047 reimari integraatio pois
finnishtransportagency/harja pull request #3029
Opened 2023-09-01 07:18 UTC by pohjamat

2023-09-04 05:34 UTC, jarnovayrynen commented on asetukset.edn
> - :reimari {:url "https://www.example.com/HarjaWebService"
Tosiaan vielä on-prem reposta kolmen eri ympäiröstön asetustiedostojen osalta päivitettävä, sekä vastaavasti kolmen eri salaisuustiedoston osalta.

2023-09-04 05:35 UTC, jarnovayrynen requested changes
Tosiaan vielä on-prem reposta kolmen eri ympäiröstön asetustiedostojen osalta päivitettävä, sekä vastaavasti kolmen eri salaisuustiedoston osalta. 

Sen jälkeen LGTM, testailin käyttöliittymällä ja asiat vaikutti yhä toimivan.

2023-09-11 06:13 UTC, pohjamat commented on asetukset.edn
> - :reimari {:url "https://www.example.com/HarjaWebService"
tästä on erillinen PR https://github.solita.fi/solita-onprem/harja-ci/pull/7

2023-09-11 06:40 UTC, jarnovayrynen approved these changes

2023-09-11 09:42 UTC, merged