VHAR-7810 & 8040 Kanavien käytettävyysparannukset
finnishtransportagency/harja pull request #3076
Opened 2023-09-28 13:39 UTC by solita-staskila

Kanavien käytettävyysparannuksia 

- Lisätty "Sulku" kohdeosille uusi toimenpide: 'Ei määritelty', jotta käyttäjä voi merkitä pelkän sillan avauksen. Eli jos kohdeosia olemassa "Silta" sekä "Sulku", käyttäjä voi merkitä 'Sillan avaus' sillan toimenpiteeksi, ja 'Ei määritelty' Sulun toimenpiteeksi, joka tarkoittaa että avattiin pelkästään silta. Ah yes, very simple.
- Lisätty ominaisuus automaattiseen ajan tallennukseen tallennushetkellä joka on optional checkbox. Käyttäjä voi valita "Käytä tallennushetken aikaa", jolloin Liikennetapahtumaa / Häiriötilannetta kirjatessa ajaksi tallennetaan se aika, kun käyttäjä painaa tallenna- näppäintä. Jos checkboxia ei ole valittuna, käyttäjä voi syöttää ajan manuaalisesti. Tämä tehtiin sen takia koska käyttäjät ovat joutuneet tekemään tuon 'ajan korjauksen' mahdollisesti kymmeniä kertoja vuoronsa aikana koska kirjaus aloitetaan aikaan X:XX, ja tallennetaan vasta myöhemmin.

2023-09-29 04:36 UTC, rckopteri commented on src/cljs/harja/tiedot/kanavat/urakka/laadunseuranta/hairiotilanteet.cljs
> +                                           @(::hairiotilanne/havaintoaika hairiotilanne))) ;; Muulloin käytetään aikakentän aika-atomia
En hoksaa, että miksi tarvitaan @ merkkiä. Ilmeisesti tallennettava-hairiotallenne saa atomin hairiotallenne?

2023-09-29 07:33 UTC, solita-staskila commented on src/cljs/harja/tiedot/kanavat/urakka/laadunseuranta/hairiotilanteet.cljs
> +                                           @(::hairiotilanne/havaintoaika hairiotilanne))) ;; Muulloin käytetään aikakentän aika-atomia
Itse hairiotilanne on mappi jossa avaimia ja arvoja, tämä ::hairiotilanne/havaintoaika avain sisältää atomin, rivi 68: 
https://github.com/finnishtransportagency/harja/pull/3076/files#diff-b79cf1800743ab477b2030331a9ba0ea54dce00f2ef8e556da5241a3a5ddefa3R68

Tämä halutaan muuttaa normaaliksi aika objektiksi kun se passataan http kutsuun, muuten siitä tulee error. Tämän takia @ merkki.  

Se taas miksi se on muunnettu atomiksi, koska frontin tee-kenttä odottaa atomia: 
https://github.com/finnishtransportagency/harja/pull/3076/files#diff-2fcfc35406fb0bdd91d399745009068317d566bfb364b47afe7eebd0cb0c6041R277

Eli tässä käytetään atomia arvon asettamiseen ja muutetaan takaisin ei-atomiksi kun siitä tehdään tallenna post kutsu.

2023-10-06 07:45 UTC, rckopteri requested changes

2023-10-06 07:45 UTC, rckopteri commented on src/cljs/harja/tiedot/kanavat/urakka/liikenne.cljs
> +    (let [app (-> app
voisi harkita myös cond-> threadin käyttöä. Silloin homma menisi auttavasti tähän suuntaan:
(cond-> app
(when jotakin (assoc :valittu-liikennetavaphtuma <jotain>))
true (assoc :siirretyt-alukset #{})
true (assoc :ketjutuksen-poistot #{})
(when (and t (::lt/aika t))) (assoc-in [:valittu-liikennetapahtuma ::lt/aika] (::lt/aika t))
)

2023-10-06 07:45 UTC, rckopteri commented on src/cljs/harja/views/kanavat/urakka/laadunseuranta/hairiotilanteet.cljs
> +                         :disabled (or
Mielipideasioita, mutta mä ehkä tykkäisin enempi, jos disabled tulisi muuttujana tähän ja päättely oltaisiin tehty esim. letin sisällä rivillä 238.

2023-10-06 07:45 UTC, rckopteri commented on src/cljs/harja/views/kanavat/urakka/laadunseuranta/hairiotilanteet.cljs
> +        :komponentti (fn []
Komponentin funktio saa kahvan lomakkeen dataan näin:
[{:keys [muokkaa-lomaketta data]}]
Tämän käyttö varmaankin säästäisi tuolta aika atomin käytöltä?

2023-10-09 09:48 UTC, solita-staskila commented on src/cljs/harja/tiedot/kanavat/urakka/liikenne.cljs
> +    (let [app (-> app
Tästä tehty cond-> macro 
https://github.com/finnishtransportagency/harja/pull/3076/commits/ad570d42cf79a088f80e86531d1281b5285cddf4

2023-10-09 09:49 UTC, solita-staskila commented on src/cljs/harja/views/kanavat/urakka/laadunseuranta/hairiotilanteet.cljs
> +                         :disabled (or
Hyvä, tuosta sai ylimääräisen letin poistettua. Huomasin samalla bugin että uusi-hairiotilanne? ei toiminut kuten odotetaan 

https://github.com/finnishtransportagency/harja/pull/3076/commits/0e68bbbe4849e6591e6cae886b9c00f84890cb99

2023-10-09 09:50 UTC, solita-staskila commented on src/cljs/harja/views/kanavat/urakka/laadunseuranta/hairiotilanteet.cljs
> +        :komponentti (fn []
Tuota en ihan kässää, komponentin `[kentat/tee-kentta {:tyyppi :pvm-aika} <#atom>]` odottaa atomia, joten meidän tulisi käyttää atomia.

2023-10-09 10:36 UTC, rckopteri approved these changes

2023-10-09 11:21 UTC, solita-staskila commented on src/cljs/harja/views/kanavat/urakka/laadunseuranta/hairiotilanteet.cljs
> +        :komponentti (fn []
Korjattu, käytetään app-staten arvoa r/wrapin kanssa atomin sijaan 
https://github.com/finnishtransportagency/harja/pull/3076/commits/84d1faf9b651c55973a9ddaf6fce333dacb77542#diff-2fcfc35406fb0bdd91d399745009068317d566bfb364b47afe7eebd0cb0c6041R296

2023-10-10 08:07 UTC, merged