VHAR-8271 Poista paikkauskustannusten kirjaamisen api-rajapinta tarpeettomana
finnishtransportagency/harja pull request #3133
Opened 2023-10-27 09:03 UTC by maaritlaine

2023-10-30 11:39 UTC, solita-staskila requested changes
Miten json-skeemat? Säilytetäänkö näitä? 
`paikkauskustannusten-kirjaus-request`
Tarviko meidän muokata api.raml tiedostoa, vai mikä tämä on? Siellä on myös tuo skeema mainittu.

2023-12-29 11:11 UTC, jpluomajoki-solita commented
Mitään ei näyttäisi hajonneen testailun perusteella. Samulin mainitsemat json-skeemat voisi poistaa, niiden jälkeen nähdäkseni tämä voitaisiin viedä tuotantoon.

2025-07-02 13:22 UTC, K1ll3rF0x commented
Vaatii uuden keskustelu poistetaanko varmasti, vai olisiko rajapinnalle sittenkin vielä käyttöä.

2025-07-21 08:50 UTC, closed without merging

2025-07-21 08:51 UTC, maaritlaine commented
Voi tulla tarpeeseen muuttuneen tilanteen takia. Konfliktejakin niin monessa tiedostossa, että kyllähän ei kannata mergeillä. Suljen pulleron pois roikkumasta.