Excel autoscale
finnishtransportagency/harja pull request #3284
Opened 2024-02-14 12:38 UTC by rckopteri

2024-02-14 13:54 UTC, solita-staskila requested changes
Tosi hienoa. Koko Exceli näyttää tällä fontilla nyt jotenkin paljon siistimmältä kuin ennen. Yhden puutteen kuitenkin huomasin, kaikkia sarakkeita ei loopata mikä pitää korjata. 

Funktiossa **_hoitokausi-kuukausi-arvotaulukko_** on nyt tämän päivityksen takia turha loop jossain rivillä 440ish, ja sen voi poistaa kokonaan: 
``
(dotimes [i (count sarakkeet)]
              (.autoSizeColumn sheet i))
``

Tässä vielä testidatalla kuinka näkyy tuo pelkästään ensimmäisten 4 sarakkeen autoskaalaus: 
![63](https://github.com/finnishtransportagency/harja/assets/116802938/7421b77e-7a99-4f1c-b21b-711d1d552363)

Ja tässä tuo ehdotettu korjattu versio, jossa kerrotaan Width 1.25, ja loopataan kaikki sarakkeet: 
![image](https://github.com/finnishtransportagency/harja/assets/116802938/7fc909c5-d111-4a47-ae4f-85338ccda3ab)


Vielä, tältä näyttää itsellä tuo 1.15 kerroin Windowssilla: 
![image](https://github.com/finnishtransportagency/harja/assets/116802938/1a8cad41-1ee5-4b2f-bd7c-338047a07cda)

Ja tässä ehdotettu 1.25: 
![image](https://github.com/finnishtransportagency/harja/assets/116802938/6cf6a33c-ed9b-4633-81c1-799484b0eec1)

2024-02-14 13:54 UTC, solita-staskila commented on src/clj/harja/palvelin/raportointi/excel.clj
> +      #_ (dotimes [i (count sarakkeet)]
Tämän voi varmaankin nyt poistaa?

2024-02-14 13:54 UTC, solita-staskila commented on src/clj/harja/palvelin/raportointi/excel.clj
> +        (.setColumnWidth sheet i (* 1.15 (.getColumnWidth sheet i)))))
Tässä nyt loopataan vain ensimmäiset 4 saraketta. Raportit joissa enemmän sarakkeita (esim. ympäristöraportti) jää nyt ilman formatointia.
Lisäksi ilmeisesti Windowsilla jotain eroja, koska itsellä jää vieläkin hieman piiloon teksti. 1.25 näyttää itselle paljon paremmalta.

Eli, tällaista korjausehdotusta:

```clojure
(doseq [sheet (excel/sheet-seq workbook)]
      (let [sarake-maara (reduce (fn [maksimi i]
                                   (if i
                                     (max maksimi (.getLastCellNum i))
                                     maksimi))
                           0
                           (excel/row-seq sheet))]
        (dotimes [i sarake-maara]
          (.autoSizeColumn sheet i)
          (.setColumnWidth sheet i (* 1.25 (.getColumnWidth sheet i))))))
```

2024-02-15 05:33 UTC, rckopteri commented on src/clj/harja/palvelin/raportointi/excel.clj
> +      #_ (dotimes [i (count sarakkeet)]
Joo. Ehkä sen uskaltaa jo poistaa :)

2024-02-15 05:44 UTC, rckopteri commented on src/clj/harja/palvelin/raportointi/excel.clj
> +        (.setColumnWidth sheet i (* 1.15 (.getColumnWidth sheet i)))))
Joo. Otin tämän käyttöön.
Aattelin, että autoskaalauksen olisi voinut aluksi pakottaa ihan vain muutamalle kolumnille, kun pääosin pitkät kolumnit on siinä alussa, kun riville annetaan nimi ja enempi lukuja lopussa.

Mutta tämä on nyt otettu käyttöön.

Poistin autoskaalauksen myös excel-raportointi/muodosta-excel :liikenneyhteenveto multimetodin alta, mutta en löytänyt itse raporttia.

2024-02-15 06:46 UTC, solita-staskila commented on src/clj/harja/palvelin/raportointi/excel.clj
> +        (.setColumnWidth sheet i (* 1.15 (.getColumnWidth sheet i)))))
Vois olla aiheellistakin tuo ensimmäisen 4 sarakkeen skaalaus, mutta jotkin raportit näyttää silloin tosi surkealta. Tuo liikenneyhteenveto on kanavaurakan liikenne- välilehti. Kävin testaamassa, näytti hyvältä.

2024-02-15 06:48 UTC, solita-staskila approved these changes
Hyvä

2024-02-15 06:51 UTC, merged