Harja-310: lupausryhma urakka taulu
finnishtransportagency/harja pull request #3297
Opened 2024-02-27 10:44 UTC by samnes

Lisätty lupausryhma_urakka taulu urakkakohtaisia lupauksia varten.
Lisätty myös uusi urakka vuodelle 2024 testidataan jotta testaaminen onnistuu helpommin uudella linkitys mallilla.

2024-02-27 11:14 UTC, solita-staskila approved these changes
Pyydä vielä toista silmäparia katsomaan

2024-02-28 06:52 UTC, jpluomajoki-solita requested changes

2024-02-28 06:52 UTC, jpluomajoki-solita commented on tietokanta/testidata/lupaus_testidata.sql
> +    (1, 43),
Älä käytä urakan ID:tä suoraan, vaan hae selectillä nimen perusteella

2024-02-28 06:52 UTC, jpluomajoki-solita commented on tietokanta/src/main/resources/db/migration/V1_1089__ .sql
> +    muokattu TIMESTAMP NOT NULL DEFAULT NOW(),
Lisää luotu timestamp

2024-02-28 13:33 UTC, jpluomajoki-solita approved these changes

2024-02-28 13:46 UTC, merged