Harja 264 xy koordinaatit suomeen
finnishtransportagency/harja pull request #3347
Opened 2024-03-27 06:27 UTC by rckopteri

2024-03-28 12:44 UTC, solita-staskila requested changes

2024-03-28 12:44 UTC, solita-staskila commented on src/cljc/harja/validointi.cljc
> +(def max-x-koordinaatti 733682)
![image](https://github.com/finnishtransportagency/harja/assets/116802938/b92f4ead-2e64-4940-8153-20b2554215dc)

Miten jos halutaan tuonne pirttykylän alueelle kirjata tarkastus, tuohan ei näy olevan koordinaattien sisällä, vaikka onkin suomessa?

2024-03-28 12:47 UTC, rckopteri commented on src/cljc/harja/validointi.cljc
> +(def max-x-koordinaatti 733682)
Mäkö otin liian kaposen alueen. Olipa hyvä tarkistus! Vähä laajennan

2024-04-03 12:27 UTC, solita-staskila approved these changes
Tämä ottaa siis tuollaisen suorakulmio alueen ja katsoo että onko koordinaatit sen sisällä? 

![image](https://github.com/finnishtransportagency/harja/assets/116802938/3a99bab3-e7e7-4ee8-bb8f-dd5be2fb1899)

Tämähän tietenkin sallii nyt hieman tuonne ruotsin/norjan/venäjän puolelle jos ollaan neliön sisällä esim. käsivarren alla, mutta ilman muuta hyvä olla tällainen validointi että ollaan kuitenkin suomen ympyrässä. Ja se että halutaanko muutenkaan ihan rajaa myöten tehdä validointi, ja kuinka monimutkaiseksi sellaisen teko sitten menisi, on toinen juttu. Annan tälle ainakin peukkua.

2024-04-04 09:41 UTC, maaritlaine approved these changes

2024-04-04 10:38 UTC, merged