Ehdotus sopimusmateriaalien resetoimisen nopeuttamiseksi
finnishtransportagency/harja pull request #3386
Opened 2024-04-19 05:21 UTC by rckopteri

2024-04-19 05:47 UTC, jarnovayrynen requested changes
Tosiaan voisi Harjaa sen verran refaktoroida, että päästään sopimus-indeksistä kokonaan eroon. Niin sen jälkeen tämä varmasti olisi tosi hyvä muutos.

2024-04-19 11:41 UTC, rckopteri commented
> Tosiaan voisi Harjaa sen verran refaktoroida, että päästään sopimus-indeksistä kokonaan eroon. Niin sen jälkeen tämä varmasti olisi tosi hyvä muutos.

Onko pakko tehdä heti, vai voidaanko tehdä vaikka kuukauden päästä?

2024-04-23 14:15 UTC, K1ll3rF0x commented
> Tosiaan voisi Harjaa sen verran refaktoroida, että päästään sopimus-indeksistä kokonaan eroon. Niin sen jälkeen tämä varmasti olisi tosi hyvä muutos.

Nyt voisi toisaalta kokeilla nopeutuuko kysely kuinka merkittävästi, kun
1. Osuu paremmin indeksiin
2. Kannassa on nyt optimaalisemmat parametrit käytössä

Minusta voidaan odottaa refaktoroinnin kanssa hieman.

2024-04-23 14:17 UTC, K1ll3rF0x approved these changes

2024-04-24 11:52 UTC, jarnovayrynen approved these changes

2024-04-24 11:58 UTC, merged