Harja 506 estä toteuman uudelleen lähetys
finnishtransportagency/harja pull request #3393
Opened 2024-04-23 06:26 UTC by rckopteri

Meille tulee tuhansia toteumia joka päivä, jotka on lähetetty jo aiemmin. Sama toteuma saatetaan lähettää kolmen kuukauden ajan. Tämä johtuu timeoutista, joka on liian lyhyt isojen toteumien käsittelemiseksi.

Tällä muutoksella varmistetaan, että yksi toteuma käsitellään vain kerran. Jos toteuma muuttuu, sen saama hash muuttuu ja näin se pääsee prosessista läpi.

2024-04-23 07:56 UTC, jarnovayrynen commented on src/clj/harja/kyselyt/toteumat.clj
> +      (log/info "Toteuma on lähetetty aiemmin. Ei tallenneta uudestaan.")
Pitäskö tähän lokittaa myös ulkoinen id, niin voidaan tarvittaessa urak. järj. henkilöille kertoa?

2024-04-23 07:56 UTC, jarnovayrynen commented on src/clj/harja/kyselyt/toteumat.clj
> +                                                                    :alkanut alkanut})))
rivityksen formatointi?

2024-04-23 07:59 UTC, rckopteri commented on src/clj/harja/kyselyt/toteumat.clj
> +                                                                    :alkanut alkanut})))
👍

2024-04-23 08:00 UTC, jarnovayrynen requested changes
Tuo json hash indeksi pitänee lisätä funktioon 
CREATE OR REPLACE FUNCTION luo_toteumataulun_partitio(alkupvm DATE, loppupvm DATE)

jotta se tulee sitten automaattisesti aina mukaan, kun luodaan uusia partitioita 250191- jälkeen. Siihenhän ei enää pitkä aika ole.

2024-04-23 08:05 UTC, rckopteri commented
> Tuo json hash indeksi pitänee lisätä funktioon CREATE OR REPLACE FUNCTION luo_toteumataulun_partitio(alkupvm DATE, loppupvm DATE)
> 
> jotta se tulee sitten automaattisesti aina mukaan, kun luodaan uusia partitioita 250191- jälkeen. Siihenhän ei enää pitkä aika ole.

Lisätty

2024-04-23 08:35 UTC, rckopteri commented on src/clj/harja/kyselyt/toteumat.clj
> +      (log/info "Toteuma on lähetetty aiemmin. Ei tallenneta uudestaan.")
Hyvä idea. Muutin samalla indeksiä, kun tuo ulkoinen-id tuli kaivettua tuohon logille.

2024-04-23 10:11 UTC, rckopteri commented on src/clj/harja/palvelin/integraatiot/api/tyokalut/apurit.clj
> +  (let [bytes (.getBytes string)]
Kokeile antaisiko digest kirjasto saman tuloksen

2024-04-24 04:24 UTC, rckopteri commented on src/clj/harja/palvelin/integraatiot/api/tyokalut/apurit.clj
> +  (let [bytes (.getBytes string)]
Antaa. Vaihdettu

2024-04-24 09:30 UTC, jarnovayrynen approved these changes

2024-04-24 09:49 UTC, merged