HARJA-464 MPU Kustannukset
finnishtransportagency/harja pull request #3398
Opened 2024-04-25 15:02 UTC by solita-staskila

2024-04-26 09:03 UTC, jpluomajoki-solita approved these changes
Näyttää hyvältä koodin ja kälin puolesta. Kaksi huomiota kuitenkin:
1. Kustannukset-välilehti on nyt viimeisenä, onko sen tarkoitus olla siellä vai pitäisikö olla aiemmmin?
 2. Kustannus voi olla miinusmerkkinen, onko se haluttu niin vai pitäisikö estää?

2024-04-26 09:03 UTC, jpluomajoki-solita commented on src/cljs/harja/tiedot/urakka/mpu_kustannukset.cljs
> +          kustannukset-yhteensa (+ kustannukset-yhteensa sanktiot)
Nämä voisi yhdistää yhdelle riville
```suggestion
          kustannukset-yhteensa (+ kustannukset-yhteensa bonukset sanktiot)
```

2024-04-26 09:03 UTC, jpluomajoki-solita commented on src/cljs/harja/views/urakka/yllapitokohteet/mpu_kustannukset.cljs
> +    (fn [e! app]
Tämä näyttää vähän turhalta välikerrokselta tässä omaan silmään. Eli `kustannukset-listaus`-ei mielestäni tarvisi olla erillinen komponentti, vaan sen sisältö voisi vaan olla tässä.

2024-05-08 03:29 UTC, solita-staskila commented on src/cljs/harja/views/urakka/yllapitokohteet/mpu_kustannukset.cljs
> +    (fn [e! app]
Minä kyllä jotenkin tykkään että nuo reagent komponentin luonnit, ja näkymän listaukset olisi aina erikseen, mutta laitoin tämän nyt vaan näin kuten sanoit

2024-05-08 03:29 UTC, solita-staskila commented on src/cljs/harja/tiedot/urakka/mpu_kustannukset.cljs
> +          kustannukset-yhteensa (+ kustannukset-yhteensa sanktiot)
Yhdistetty

2024-05-08 03:31 UTC, solita-staskila commented
> Kustannukset-välilehti on nyt viimeisenä, onko sen tarkoitus olla siellä vai pitäisikö olla aiemmmin?

    Laitettu Figman mukaiseksi

> Kustannus voi olla miinusmerkkinen, onko se haluttu niin vai pitäisikö estää?

    Selvitän

2024-05-08 05:48 UTC, jpluomajoki-solita requested changes
Suurimmaksi osaksi näyttää hyvältä. Muutamia pieniä kommentteja lähinnä koodin siistimiseen. Kaksi tärkeämpää huomiota: Urakan vaihtaminen ei nollaa tilaa ja urakat näkevät toistensa selitteet. Eli jos selitteeksi laitetaan jotain urakkaspesifiä (Esim. "Jarnon traktorin hinaus", se näkyy myös muille urakoille. Uskon vahvasti, että siinä voi olla isokin riski ja se pitäisi ehdottomasti estää.

2024-05-08 05:48 UTC, jpluomajoki-solita commented on dev-resources/less/pages/mpu_kustannukset.less
> +  h3 { margin: 0 }
Tämän voisi korvata laittamalla h3-elementille luokan `ei-marginia`

2024-05-08 05:48 UTC, jpluomajoki-solita commented on src/clj/harja/kyselyt/mpu_kustannukset.clj
> +  (defqueries "harja/kyselyt/mpu_kustannukset.sql"
Sisennykset taitaa olla pielessä

2024-05-08 05:48 UTC, jpluomajoki-solita commented on src/clj/harja/kyselyt/mpu_kustannukset.sql
> +SELECT DISTINCT(selite) FROM mpu_kustannukset;
Mielestäni tämä kaipaisi edelleen urakkakohtaisuutta ellei ole erikseen päätetty toisin

2024-05-08 05:48 UTC, jpluomajoki-solita commented on src/cljs/harja/tiedot/urakka/mpu_kustannukset.cljs
> +  (:require [reagent.core :refer [atom] :as reagent]
```suggestion
  (:require [reagent.core :refer [atom]]
```
`reagent`ia ei käytetä, eli tuo :as jälkeinen osa on käyttämätön import

2024-05-08 05:48 UTC, jpluomajoki-solita commented on src/cljs/harja/tiedot/urakka/mpu_kustannukset.cljs
> +    (assoc app :muokataan true))
Kun urakkaa vaihdetaan, tämä jää päälle. Pitäisi siis nollata tila urakkaa vaihtaessa

2024-05-08 05:48 UTC, jpluomajoki-solita commented on src/cljs/harja/views/urakka/yllapitokohteet/mpu_apurit.cljs
> +            [harja.ui.yleiset :refer [ajax-loader] :as yleiset]
```suggestion
            [harja.ui.yleiset :refer [ajax-loader]]
```
Käyttämätön require

2024-05-08 05:48 UTC, jpluomajoki-solita commented on src/cljs/harja/views/urakka/yllapitokohteet/mpu_kustannukset.cljs
> +            [harja.ui.yleiset :refer [ajax-loader] :as yleiset]
```suggestion
            [harja.ui.yleiset :refer [ajax-loader]]
```

2024-05-14 10:14 UTC, solita-staskila commented on dev-resources/less/pages/mpu_kustannukset.less
> +  h3 { margin: 0 }
Korjattu

2024-05-14 10:14 UTC, solita-staskila commented on src/clj/harja/kyselyt/mpu_kustannukset.clj
> +  (defqueries "harja/kyselyt/mpu_kustannukset.sql"
Korjattu

2024-05-14 10:14 UTC, solita-staskila commented on src/clj/harja/kyselyt/mpu_kustannukset.sql
> +SELECT DISTINCT(selite) FROM mpu_kustannukset;
Kyllä, oli unohtunut. Korjattu

2024-05-14 10:14 UTC, solita-staskila commented on src/cljs/harja/tiedot/urakka/mpu_kustannukset.cljs
> +  (:require [reagent.core :refer [atom] :as reagent]
Korjattu

2024-05-14 10:15 UTC, solita-staskila commented on src/cljs/harja/tiedot/urakka/mpu_kustannukset.cljs
> +    (assoc app :muokataan true))
Korjattu

2024-05-14 10:15 UTC, solita-staskila commented on src/cljs/harja/views/urakka/yllapitokohteet/mpu_apurit.cljs
> +            [harja.ui.yleiset :refer [ajax-loader] :as yleiset]
Korjattu

2024-05-14 10:15 UTC, solita-staskila commented on src/cljs/harja/views/urakka/yllapitokohteet/mpu_kustannukset.cljs
> +            [harja.ui.yleiset :refer [ajax-loader] :as yleiset]
Korjattu

2024-05-14 11:09 UTC, jpluomajoki-solita approved these changes

2024-05-14 11:25 UTC, merged