Harja 474 poista suunnittelutiedot
finnishtransportagency/harja pull request #3429
Opened 2024-05-27 09:27 UTC by rckopteri

Poistetaan rahavaraustehtäviltä suunnittelutiedot Toteuma/Tehtävät sivulta. Rahavarauksille ei suunnitella määriä, vaan euroja. Ja niille kirjataan vain kuluja, mutta jos niille erehtyy kirjaamaan toteumia toteuma_tehtävät tauluun, niin ei verrata niitä suunniteltuihin lukuihin, koska niitä ei voi Suunnittelu/Tehtävät sivulla suunnitella.

Tässä samassa pr:ssä on myös hallintapaneeliin lisätty urakkakohtainen nimi rahavarauksille.
Sekä mahdollisuus poistaa rahavarauksia. Eli se hallinnan rahavaraussivu meni käytännössä kokonaan uusiksi.

2024-05-28 15:21 UTC, solita-staskila requested changes
Näyttää ihan hyvältä, käyttöliittymän puolella hieman korjattavaa ainakin tuo toimimaton rivin lisäys ja tallennusviesti, sekä ajax loaderin puute. 

Olisiko rahavarauksen poistolle järkevää tehdä käyttäjältä varmistus? Meillä ainakin löytyy tuollainen **varmista-kayttajalta** wrapper, tuo voi olla aika paha jos jostain syystä vahingossa painaa poista nappia ja rahavaraus lähtee suoraa lentoon.

2024-05-28 15:21 UTC, solita-staskila commented on src/clj/harja/kyselyt/rahavaraukset.sql
> +-- name: poista-rahavaraus!
Kun meillä on nyt mahdollista poistaa ja lisätä rahavaraus taulusta tavaraa, onko aiheellista tehdä jokin triggeri, joka ajaa esim populoi_rahavaraus_idt() ? Entä rahavaraus_urakka taulu, onko tänne mahdollista jäädä rahavarauksia urakoille, joita ei enää ole olemassa tms?

2024-05-28 15:21 UTC, solita-staskila commented on src/clj/harja/palvelin/palvelut/hallinta/rahavaraukset.clj
> +        uusi-rivi (and (not (nil? id)) (= -1 id))
Oisko sama olla (some? id) ?

2024-05-28 15:21 UTC, solita-staskila commented on src/clj/harja/palvelin/palvelut/hallinta/rahavaraukset.clj
> +                   (and (nil? valittu?) (not (nil? urakkakohtainen-nimi)))
Tässä myös? + typo tuossa ylhäällä olevassa kommentissa

2024-05-28 15:21 UTC, solita-staskila commented on src/cljs/harja/tiedot/hallinta/rahavaraukset.cljs
> +      :valittu-urakka (or (:valittu-urakka app) (first urakat)))))
Voisko destructoida funktion parametreissa molemmat vastaus sekä app, josta haetaan näitä avaimien arvoja

2024-05-28 15:21 UTC, solita-staskila commented on src/cljs/harja/tiedot/hallinta/rahavaraukset.cljs
> +         :nimi (:nimi rahavaraus)
Voisko nämäkin tuon letin sisällä vielä destruktoida, joteinkin
```clojure
(let [{:keys [id nimi]} rahavaraus
;; ... 
]
```

Mutta suoraan sanottuna en nyt ole ihan varma. On OK kai näinkin.

2024-05-28 15:21 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/rahavaraukset.cljs
> +                           (js/console.log "uusi rivi :: rivi:" (pr-str rivi))
Nämä console debuggaukset voi varmaan heittää kuikaan jo, ellei ole jotain tärkeää logitusta

2024-05-28 15:21 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/rahavaraukset.cljs
> +                                 [:label {:for id} "" #_(:nimi rivi)]]))}
Kommentoidun rivin voi poistaa

2024-05-28 15:21 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/rahavaraukset.cljs
>      (fn [e! {:keys [valittu-urakka urakat urakoiden-rahavaraukset rahavaraukset tallennukset-kesken] :as app}]
tallennukset-kesken ei käytetä, tämän voisi ottaa käyttöön, ja lisätä ajax-loader näkymään, jos tallennus on kesken tai haku on käynnissä

2024-05-28 15:21 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/rahavaraukset.cljs
> +  (:require [reagent.core :refer [atom] :as r]
:refer [atom] ei tarvitse, sama alemmassa tuck.core :refer send-value!, send-async!

2024-05-28 15:21 UTC, solita-staskila commented on src/cljs/harja/tiedot/hallinta/rahavaraukset.cljs
> +        {:urakka (:urakka-id valittu-urakka)
Urakka passattu turhaan? Ei taideta käyttää koko palvelussa.

2024-05-28 15:21 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/rahavaraukset.cljs
> +              :voi-lisata? true
Lisäys ei tee mitään? 
:uusi-rivi funktion logitus tulee consoleen, mutta pitäisikö taulukossa näkyä jotain?

2024-05-28 15:21 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/rahavaraukset.cljs
> +              :on-rivi-blur (fn [rivi _]
Lisää tähän jokin toast viesti onnistuneesta / epäonnistuneesta tallennuksesta. Kun taulukkoa muokkaa joko kirjoittamalla urakkakohtainen nimi kenttään, tai laittamalla täppiä, muutos tulee kantaan mutta käyttäjälle ei näy mitään viestiä tästä.

Tai sitten erillinen tallenna nappi?

2024-05-31 04:27 UTC, rckopteri commented on src/clj/harja/kyselyt/rahavaraukset.sql
> +-- name: poista-rahavaraus!
Näkisin, että tuo triggeri on turha, koska sitä populointia tarvitaan vain vanhoille rahavarauksille. Jos uusia luodaan, niin niille voi lisätä kulun vasta sen jälkeen, kun se uusi rahavaraus ilmestyy sinne kulu sivulle.

Rahavarauksen poiston yhteydessä varmistetaan ensin, että rahavaraus ei ole käytössä ja jos se ei ole, niin sen tehtävät poistetaan, se poistetaan urakoilta ja sen jälkeen itse rahavaraus poistetaan.

2024-05-31 04:32 UTC, rckopteri commented on src/cljs/harja/tiedot/hallinta/rahavaraukset.cljs
> +      :valittu-urakka (or (:valittu-urakka app) (first urakat)))))
urakoiden-rahavaraukset lisätty desctructuroinnilla funktion parametriin

2024-05-31 04:33 UTC, rckopteri commented on src/cljs/harja/tiedot/hallinta/rahavaraukset.cljs
> +         :nimi (:nimi rahavaraus)
Niitä kaikkia käytetään kerran. En näe hyötyä lisätä destructuroinnin monimutkaisuutta.

2024-05-31 04:34 UTC, rckopteri commented on src/cljs/harja/views/hallinta/rahavaraukset.cljs
> +                           (js/console.log "uusi rivi :: rivi:" (pr-str rivi))
Poistettu.

2024-05-31 04:34 UTC, rckopteri commented on src/cljs/harja/views/hallinta/rahavaraukset.cljs
> +                                 [:label {:for id} "" #_(:nimi rivi)]]))}
Poistettu

2024-05-31 04:39 UTC, rckopteri commented on src/cljs/harja/views/hallinta/rahavaraukset.cljs
>      (fn [e! {:keys [valittu-urakka urakat urakoiden-rahavaraukset rahavaraukset tallennukset-kesken] :as app}]
Jätin ihan tarkoituksella tämän pois, koska olisi lisännyt vain turhaa kehitysaikaa fiitserille, joka muutenkin laajeni jo alkuperäisestä valtavasti.

2024-05-31 04:41 UTC, rckopteri commented on src/cljs/harja/views/hallinta/rahavaraukset.cljs
> +  (:require [reagent.core :refer [atom] :as r]
:refer atom  , send-async! ja send-value! jätetty pois

2024-05-31 04:42 UTC, rckopteri commented on src/cljs/harja/tiedot/hallinta/rahavaraukset.cljs
> +        {:urakka (:urakka-id valittu-urakka)
👍  Jes. Poistettu.

2024-05-31 04:43 UTC, rckopteri commented on src/cljs/harja/views/hallinta/rahavaraukset.cljs
> +              :voi-lisata? true
Muokkausgridissä uusin rivi tulee aina sinne pohjalle.

2024-05-31 09:44 UTC, rckopteri commented on src/cljs/harja/views/hallinta/rahavaraukset.cljs
> +              :on-rivi-blur (fn [rivi _]
Muutin muokkaus-gridin perus gridiksi, jossa on tallenna -napille ihan erilainen toimintatapa.
En ollut tiennyt, että perusgridilläkin voi muokata juttuja. Se on paljon helpompikäyttöinen tällaiseen.

2024-05-31 14:28 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/rahavaraukset.cljs
>      (fn [e! {:keys [valittu-urakka urakat urakoiden-rahavaraukset rahavaraukset tallennukset-kesken] :as app}]
Lisäsin hyrrän

2024-05-31 14:40 UTC, solita-staskila approved these changes
## Huomiot:
- ### Funktio paivita-urakan-rahavaraus<! ei pysty päivittämään rahavarauksen nimeä - onko tämä tarkoituksella? 

- ### Kun gridiin lisätään uusi rivi, urakkakohtaista nimeä ei pysty antamaan - onko tarkoituksenmukaista? Jos on, voisko tämän vaikka jotenkin blurrata? 


Muuten nyt OK. Kävin sorkkimassa hieman koodia hyvässä yhteistyöhengessä, toivottavasti ei haittaa 😃 Jos silmäilet vielä itse nuo minun tekemät muutokset? 

Lisäsin tuon ajax-loaderin, korjasin tallennuksen No protocol- virheen, poistin checkboxin käytöstä kun muokkaus on päällä (tämä johtaa muuten virheeseen), ja lisäsin tuon käyttäjältä varmistuksen jos rahavarauksia poistetaan niin nyt niitä ei ainakaan vahingossa lähde lentoon.

2024-06-07 09:11 UTC, merged