Reikäpaikkausten vienti exceliin käyttäen pohjaa
finnishtransportagency/harja pull request #3483
Opened 2024-07-31 12:10 UTC by jpluomajoki-solita

2024-08-01 10:06 UTC, rckopteri approved these changes

2024-08-05 04:54 UTC, solita-staskila requested changes
Hienoa, muuten toimii mutta tuolle päivämäärälle pitäisi jotain keksiä. Tässä kuva mistä kyse 

![image](https://github.com/user-attachments/assets/ea543cf3-455a-4e1a-921a-4c8ce424feb5)

2024-08-05 04:54 UTC, solita-staskila commented on src/clj/harja/palvelin/palvelut/yllapitokohteet/paikkauskohteet_excel.clj
> +        excel-nimi (str urakka " reikäpaikkaukset")
Tiedostonimeen voisi vielä aikavälin laittaa kun tämä on olemassa muuallakin Harjassa, mutta lähinnä vaan ehdotus

2024-08-05 04:54 UTC, solita-staskila commented on src/clj/harja/palvelin/palvelut/yllapitokohteet/paikkauskohteet_excel.clj
> +                              alkuaika
Päivämäärän vienti tulee tällaisessa muodossa Exceliin "3/5/2024" (tässä voi olla käyttäjän käyttöjärjestelmä-eroja), joka ei toimi Excel-tuonnissa. Oikea formaatti joka ainakin toimii olisi "dd.mm.yyyy". Eli jos tuonnissa käyttää tätä viennin generoimaa tiedostoa, tuo päivämäärä ei tule perille

2024-08-05 11:29 UTC, jpluomajoki-solita commented on src/clj/harja/palvelin/palvelut/yllapitokohteet/paikkauskohteet_excel.clj
> +                              alkuaika
Formaatti riippuu juurikin excelin asetukista. Itse laitoin sen käyttämään suomen formaattia, ja sillä tuonti toimii. Parempi kuitenkin selvittää saisiko tuon pakotettua suomen formaattiin, jolloin tuonti toimisi riippumatta käyttäjän omista asetuksista.

2024-08-05 11:30 UTC, jpluomajoki-solita commented on src/clj/harja/palvelin/palvelut/yllapitokohteet/paikkauskohteet_excel.clj
> +        excel-nimi (str urakka " reikäpaikkaukset")
Aikavälin lisäys tiedostonimeen tuntui aika haastavalta, kun ajassa voi olla vain alku tai loppu, molemmat tai ei kumpaankaan. En keksinyt, miten näyttää pvm kun toinen puuttuu, joten jätin sen kokonaan pois.

2024-08-06 06:23 UTC, jpluomajoki-solita commented on src/clj/harja/palvelin/palvelut/yllapitokohteet/paikkauskohteet_excel.clj
> +                              alkuaika
Formatointi päivitetty, kokeiletko nyt miten toimii sun koneella?

2024-08-06 08:16 UTC, solita-staskila approved these changes
Hyvä, nyt toimii

2024-08-07 12:08 UTC, merged