Kasvata sallittua pdf-rivimäärää
finnishtransportagency/harja pull request #3522
Opened 2024-09-12 09:22 UTC by maaritlaine

2024-09-12 10:44 UTC, solita-staskila approved these changes
Mikä raportti generoi näin monta riviä, että rajoitus nostetaan 100k? Kanavissa esim, olen huomannut että raportin suoritukseen alkaa menemään kauemman aikaa jos generoidaan kymmeniätuhansia rivejä, tämmöinen oli mahdollista liikenne välilehdellä, ja olen rajoittanut sen 10k: +rajoita-tapahtumien-maara+, riippuu raportista tietenkin, kauanko siinä kestää

Mutta jos tämä on testattu ja todettu toimivaksi niin OK.

2024-09-12 13:10 UTC, solita-staskila requested changes
> WARN ADMIN [harja.palvelin.palvelut.selainvirhe:31] - 0:0:0:0:0:0:0:1 8578d6a8-7420-4f70-be13-2222eb7a8ab2 Jarjestelmavastaava {:text "Käyttäjä Jarjestelmavastaava (13728483) raportoi yhteyskatkoksista palveluissa:", :fields [{:title ":ping", :value "Katkoksia 1 kpl|||ensimmäinen: 2024-09-12T12:57:05.000Z|||viimeinen: 2024-09-12T12:57:05.000Z"}]}

https://github.com/user-attachments/assets/6e2189e1-37c2-433e-b3f1-244f092ac0eb

Otan tämän takaisin. Exceli kestää kyllä helpommin enemmän rivejä, mutta PDF generointi menee omassa kehitysympäristössä kohtuttoman hitaaksi jo tuossa 1200 rivin kohdalla jos yrittää generoida noin 15 tuhatta riviä. Minä en ole varma miten tuo AWS tuotannon ympäristössä suoriutuu, mutta en ehkä laittaisi noin isoa rajaa tuonne PDF raporttiin. 

Siellä on olemassa teksti:

> "Taulukossa näytetään vain ensimmäiset " +max-rivimaara+ " rivia. "

Johon voisi ohjeistaa käyttäjää ajamaan vaikka sitä Excel raporttia? Voisi tiimiä pyytää apuun, omalla testauksella ympäristö meni ainakin aivan tukkoon tällä rajalla. Minulla voi olla vaan surkea kone kun tämä pyörii Windowsin päällä niin en osaa nyt varmasti sanoa tuleeko tästä tuotantoon ongelmia. En nyt päästä kuitenkaan jatkoon.

2024-09-13 15:08 UTC, solita-staskila commented
Alkuperäinen muutos https://github.com/finnishtransportagency/harja/pull/3522/commits/1abe7c406594352134db5784b1fac8d0d21d9d61 mahdollisti JVM runtime muistin liiaallisen allocaation yhdelle käyttäjälle. Korjauksena lisätty mahdollisuus asettaa PDF raporteille rivimääräraja erikseen, oletusarvona 1 000. 

Tiestötarkastuksille rarja  asetettu 30 000 riviin, koska tämä näyttää toimivan vielä suhteellisen hyvin mutta en menisi tuota korkeammalle. Jos rivimäärä ylittyy, PDF pohjalla näkyy viesti joka ohjaa käyttäjää ajamaan Excel raportin tai pienentämään hakuehtoja. Excel ajaminen ei laita runtime muistia tukkoon.

Mikäli jollekin raportille halutaan kasvattaa tuota rajaa, tätä tulisi testata perusteellisesti, koska muistin toiminta voi vaihdella raporttikohtaisesti.

2024-09-17 05:15 UTC, rckopteri commented
> Alkuperäinen muutos [1abe7c4](https://github.com/finnishtransportagency/harja/commit/1abe7c406594352134db5784b1fac8d0d21d9d61) mahdollisti JVM runtime muistin liiaallisen allocaation yhdelle käyttäjälle. Korjauksena lisätty mahdollisuus asettaa PDF raporteille rivimääräraja erikseen, oletusarvona 1 000.
> 
> Tiestötarkastuksille rarja asetettu 30 000 riviin, koska tämä näyttää toimivan vielä suhteellisen hyvin mutta en menisi tuota korkeammalle. Jos rivimäärä ylittyy, PDF pohjalla näkyy viesti joka ohjaa käyttäjää ajamaan Excel raportin tai pienentämään hakuehtoja. Excel ajaminen ei laita runtime muistia tukkoon.
> 
> Mikäli jollekin raportille halutaan kasvattaa tuota rajaa, tätä tulisi testata perusteellisesti, koska muistin toiminta voi vaihdella raporttikohtaisesti.

Löysit tuon 30 000 rajan lokaalikoneella? Vai ajelitko tuotantoa vastaavalla värkillä? Koneet on äkkikseltään aika erilaisia, niin sen takia varmistelen.

2024-09-17 05:18 UTC, rckopteri approved these changes

2024-09-17 07:45 UTC, solita-staskila commented
> Löysit tuon 30 000 rajan lokaalikoneella? Vai ajelitko tuotantoa vastaavalla värkillä? Koneet on äkkikseltään aika erilaisia, niin sen takia varmistelen.

En huomannut siis tuossa tiestötarkastuksissa mitään ongelmaa muistin kanssa. Uusimaa 2023 tammikuun tarkastusajot rivejä on noin 20 000, rapsan teko kestää vähän mutta tämä suoriutuu kyllä ihan nätisti.  En menisi tuota 30 000 korkeammalle kuitenkaan varmuuden vuoksi, ja myös sen takia kun siinä alkaa kestämään kauemmin.

Tuo muistin toiminta näyttää olevan raporttikohtainen, ongelmallinen raportti oli kanavien liikenne-välilehdellä,  jos urakoita valitsee monta ja vuosi 2023, lokaali järjestelmä  kaatuu jo 10k rivimäärällä. Lokaalisti itsellä on 2 gigaa varattuna JVM muistia, tuotannossa tuota on 10 gigaa  joten siellä ei välttämättä järjestelmä kaadu mutta ei haluta tehdä mahdolliseksi että 1 käyttäjä allocoi kaiken muistin.

2024-09-18 11:31 UTC, solita-staskila approved these changes

2024-09-18 11:42 UTC, merged