Tiedon laadun POC HARJA 705
finnishtransportagency/harja pull request #3558
Opened 2024-09-23 10:41 UTC by jarnovayrynen

2024-10-07 07:23 UTC, solita-staskila requested changes

2024-10-07 07:23 UTC, solita-staskila commented on src/cljs/harja/views/hallinta.cljs
> +    :kojelauta
Olisko  välilehden nimelle "Urakoiden tilanne" parempi vaan "Kojelauta" tms, kun tämä resonoi ja olisi yhtenäinen myös koodin sekä tiksujen kanssa, kuten tässä tiedostossa muutkin tabit on nimetty. On OK näinkin.

2024-10-07 07:23 UTC, solita-staskila commented on src/cljs/harja/views/hallinta.cljs
> +    (when (oikeudet/hallinta)
Oisko tälle pitänyt laittaa ne järjestelmävastaavan oikeudet?
![image](https://github.com/user-attachments/assets/953d5d1e-75f8-4a6a-a3ef-53392fa1d8e4)

2024-10-07 07:23 UTC, solita-staskila commented on dev-resources/less/pages/kojelauta.less
> +.kojelauta-hallinta {
Täällä ei oo mitään. Tänne  varmaan tulevaisuudessa tulossa jotain?

2024-10-07 07:23 UTC, solita-staskila commented on src/clj/harja/kyselyt/kojelauta.sql
> +     (:hoitokauden_alkuvuosi BETWEEN
Tässä vähän koodin ja formatoinnin kanssa epäsynkkaa. BETWEEN clausea voi  simplifioida, siellä turhaa selectiä. 
Onko tässä jokin syy miksi parametri on definattu näin?: **_:hoitokauden_alkuvuosi AS hoitokauden_alkuvuosi_** 

Tässä kuitenkin vähän selvempi versio tuolle WHERE iffitelyyn:

```sql
-- name: hae-urakat-kojelautaan
SELECT u.id,
       u.nimi,
       u.hallintayksikko AS ely_id,
       :hoitokauden_alkuvuosi AS hoitokauden_alkuvuosi,
       urakan_kustannussuunnitelman_tila(u.id::INTEGER,
                                         monesko_hoitokausi(u.alkupvm, u.loppupvm, :hoitokauden_alkuvuosi::INTEGER)) AS ks_tila
  FROM urakka u
           JOIN organisaatio o ON u.hallintayksikko = o.id
 WHERE u.tyyppi = 'teiden-hoito' 
   AND (:hoitokauden_alkuvuosi BETWEEN EXTRACT(YEAR FROM u.alkupvm) AND EXTRACT(YEAR FROM u.loppupvm) - 1)
   AND (:urakat_annettu IS NOT TRUE OR u.id IN (:urakka_idt)) 
   AND (:ely_id::INTEGER IS NULL OR u.hallintayksikko = :ely_id);
```

2024-10-07 07:23 UTC, solita-staskila commented on src/clj/harja/palvelin/palvelut/hallinta/kojelauta.clj
> +            [harja.kyselyt.konversio :as konv]
Konversio includattu kahdesti

2024-10-07 07:23 UTC, solita-staskila commented on src/clj/harja/palvelin/palvelut/hallinta/kojelauta.clj
> +                                               :urakat_annettu (boolean (not (empty? urakka-idt)))
(not (empty?  
->
(seq

2024-10-07 07:23 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/kojelauta.cljs
> +                                    (prn "Jarno on click! urakassa " (:id rivi) " ja elyssä " (:ely_id rivi))
Tämän voi varmaan nyt poistaa

2024-10-07 07:23 UTC, solita-staskila commented on src/cljs/harja/tiedot/urakka/siirtymat.cljs
> +(defn kustannusten-seurantaan-valitussa-urakassa [hallintayksikko-id urakka-id]
TypeError: Cannot read properties of undefined (reading 'call')
TMLUnknownElement.callCallback

2024-10-07 07:23 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/kojelauta.cljs
> +            [harja.tiedot.hallintayksikot :as hy]
Hallintayksiköt sekä yleiset on requirattu kahdesti. Valinnat on turha require.

2024-10-07 07:23 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/kojelauta.cljs
> +    [:label.alasvedon-otsikko-vayla {:for "urakkahaku"} "Hae urakkaa"]
Kun alasvetoa klikkaa, se ei mene enää kiinni (jos klikkaat alasvetoa vaikka uudelleen) kun vasta sitten kun klikkaat ulkopuolelle, mutta en nyt ala tästä nillittämään, on ihan OK näinkin. Jos kuitenkin näät  helpoksi fixata niin fixaa

2024-10-07 07:23 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/kojelauta.cljs
> +(defn- mahdolliset-hoitokauden-alkuvuodet [pvm-nyt]
Tässä on vaan nykyvuosi - 2 vuotta -> nykyvuosi +6 vuotta. Halutaanko näin, onko tämä jossain speksissä?

2024-10-07 07:23 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/kojelauta.cljs
> +(defn listaus [e! {:keys [valinnat urakat urakoiden-tilat] :as app}]
Ainakin urakoiden tilat on turha destruktointi, eli turha muuttuja. e!  sekä appi saa kyllä olla läsnä tässä

2024-10-07 07:23 UTC, solita-staskila commented on tietokanta/src/main/resources/db/migration/R__Kojelauta.sql
> +
Onko tässä lentokoneelle  varattu laskeutumispaikka kun whitespacea sen verran 😃

2024-10-07 07:23 UTC, solita-staskila commented on tietokanta/src/main/resources/db/migration/R__Kojelauta.sql
> +      INTO vahvistamattomia;
Näihin muuttujiin: vahvistettuja vahvistamattomia 
Oisko tässä selectissä hyvä käyttää COALESCE(x, 0), jos tämä palauttaa nullia

2024-10-07 07:23 UTC, solita-staskila commented on tietokanta/src/main/resources/db/migration/R__Kojelauta.sql
> +    aloittamattomia := kaikkien_osioiden_lkm_per_hoitokausi - vahvistamattomia - vahvistettuja;
Edelliseen kommenttiin, tässäkin oletetaan että nämä sisältää aina integer numeroita, COLESCE olisi hyvä  laittaa väliin

2024-10-07 07:23 UTC, solita-staskila commented on tietokanta/src/main/resources/db/migration/R__Kojelauta.sql
> +$$ LANGUAGE plpgsql;
Tämmösiä ehdotuksia tuohon funkkariin, olisko vähän selvempikin näin:
```sql
SELECT COALESCE(count(*), 0) INTO vahvistettuja FROM suunnittelu_kustannussuunnitelman_tila
WHERE hoitovuosi = _hoitovuosi AND urakka = _urakka AND vahvistettu IS TRUE;

SELECT COALESCE(count(*), 0) INTO vahvistamattomia FROM suunnittelu_kustannussuunnitelman_tila
WHERE hoitovuosi = _hoitovuosi AND urakka = _urakka AND vahvistettu IS FALSE;

aloittamattomia := kaikkien_osioiden_lkm_per_hoitokausi - COALESCE(vahvistettuja, 0) - COALESCE(vahvistamattomia, 0);
```

2024-10-07 07:23 UTC, solita-staskila commented on tietokanta/src/main/resources/db/migration/R__Kojelauta.sql
> +                                                               (EXTRACT(YEAR FROM loppupvm)::INTEGER - 1))), hoitokauden_alkuvuosi) into jarjestysluku;
Pientä pilkunviilausta, täällä on joitain SQL statementteja lowercasella, laitatko nämä uppercaseksi :D

2024-10-07 07:23 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/kojelauta.cljs
> +    (komp/sisaan #(e! (tiedot/->HaeUrakat)))
Lisää ajax loaderi kun urakoita haetaan, tuohon HaeUrakat assoccaa haku-kaynnissa? true, ja calbackkiin false. 

Sitten Gridi näytetään jos:
```clojure
(if haku-kaynnissa?
       [:div.ajax-loader-valistys
        [ajax-loader-pieni (str "Haetaan tietoja...")]]
```

Tätä on yritettykin lisätä tuonne :tyhja parametriin, mutta se ei toimi. Testattu kloonia vasten.

2024-10-07 07:23 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/kojelauta.cljs
> +       [debug/debug app]
Poista kaikki nämä debug komponentit, tai lisää iffi jos ollaan kehitysympäristössä, kun nämä on nyt menossa tuotantoon asti. Näitä on 2 kappaletta.

2024-10-07 07:54 UTC, K1ll3rF0x commented on src/cljs/harja/tiedot/hallinta/kojelauta.cljs
> +(defrecord Valitse [avain valinta])
MItä tässä valitaan?

2024-10-07 07:56 UTC, K1ll3rF0x commented on src/cljs/harja/tiedot/hallinta/kojelauta.cljs
> +    (js/console.error "Virhe urakoiden haussa!" vastaus)
Voisi käyttää normaalia timbren lokitusta.

2024-10-08 05:26 UTC, jarnovayrynen commented on src/cljs/harja/views/hallinta.cljs
> +    :kojelauta
Käytiin tästä nimestä Slackissä keskustelua, ja lopputulema oli tämä Urakoiden tilanne. Se on kohdeyleisölle selkeämpi kuin Kojelauta, vaikka meille devareille ei välttämättä olekaan. :)

2024-10-08 05:28 UTC, jarnovayrynen commented on dev-resources/less/pages/kojelauta.less
> +.kojelauta-hallinta {
Poistetaanpa turha filu, lisätään sitten jos joskus tarvetta.

2024-10-08 05:30 UTC, jarnovayrynen commented on src/clj/harja/kyselyt/kojelauta.sql
> +     (:hoitokauden_alkuvuosi BETWEEN
Hyvä parannus, kiitos. 🎉

2024-10-08 05:33 UTC, jarnovayrynen commented on src/cljs/harja/views/hallinta.cljs
> +    (when (oikeudet/hallinta)
Tää oikeudet/hallinta on nimenomaan "vain Järjestelmävastaava" eli 
`(in-ns 'harja.domain.oikeudet)
=> #namespace[harja.domain.oikeudet]
hallinta
=> #harja.domain.oikeudet.KayttoOikeus{:kuvaus "Osio Hallinta", :roolien-oikeudet {"Jarjestelmavastaava" #{"R*" "W*"}}}`

2024-10-08 05:37 UTC, jarnovayrynen commented on src/cljs/harja/views/hallinta/kojelauta.cljs
> +                                    (prn "Jarno on click! urakassa " (:id rivi) " ja elyssä " (:ely_id rivi))
kyllä

2024-10-08 05:38 UTC, jarnovayrynen commented on src/clj/harja/palvelin/palvelut/hallinta/kojelauta.clj
> +                                               :urakat_annettu (boolean (not (empty? urakka-idt)))
kyllä, kiitos

2024-10-08 08:54 UTC, jarnovayrynen commented on src/cljs/harja/tiedot/hallinta/kojelauta.cljs
> +    (js/console.error "Virhe urakoiden haussa!" vastaus)
poistetaan koko lokitus turhana

2024-10-08 09:17 UTC, jarnovayrynen commented on src/cljs/harja/views/hallinta/kojelauta.cljs
> +    (komp/sisaan #(e! (tiedot/->HaeUrakat)))
Hyvin havaittu. Aiemmin on usein asetettu arvo nil:iin siihen asti kun vastausta ei ole, mutta tässä tapauksessa se ei toimi, joten lisäsin tämän haku-kaynnissa? option. 👍

2024-10-08 09:17 UTC, jarnovayrynen commented on src/cljs/harja/tiedot/hallinta/kojelauta.cljs
> +(defrecord Valitse [avain valinta])
Asetetaan suodatin, joten vaihdoin eventin nimeksi AsetaSuodatin 👍

2024-10-09 06:05 UTC, jarnovayrynen commented on src/cljs/harja/views/hallinta/kojelauta.cljs
> +(defn- mahdolliset-hoitokauden-alkuvuodet [pvm-nyt]
Juteltiin UX:n kanssa, todettiin että 4 vuotta taaksepäin ja 6 eteenpäin. Korjattu

2024-10-09 06:30 UTC, solita-staskila approved these changes
On hyvä. Kun tullaan näkymään ja valitaan urakka tuosta hausta, tulee vielä consoleen  react erroria:
> A component is changing an uncontrolled input

En nää tätä kovin hyvänä, tämä pitäisi ainakin jossain kohti  saada siivottua.

2024-10-09 06:30 UTC, solita-staskila commented on src/cljs/harja/views/hallinta/kojelauta.cljs
> +  (:require-macros [harja.tyokalut.ui :refer [for*]]))
Täällä vielä turha macro sekä debug requirattuna

2024-10-10 09:35 UTC, jarnovayrynen commented on src/cljs/harja/views/hallinta/kojelauta.cljs
> +  (:require-macros [harja.tyokalut.ui :refer [for*]]))
makro pois, debug näkyy olevan tapana jättää tonne, ja varsinkin nyt kehityksessä sitä tulee käytettyä koko ajan, niin jättäisin

2024-10-10 13:41 UTC, merged