Harja 974 - Alleviivaukset lisätty linkkeihin ilman hoveria.
finnishtransportagency/harja pull request #3741
Opened 2024-11-29 11:35 UTC by solita-laurin

2024-11-29 12:49 UTC, solita-staskila requested changes

2024-11-29 12:49 UTC, solita-staskila commented on src/cljs/harja/ui/yleiset.cljs
> +  [:a.klikattava.alleviivaa {:href linkki
Onko meillä tollasta classia olemassa? Miksi minä en nyt löydä? Tuleeko tää jostain piilosta? Mitä propertyja tolla classilla on? 

Jos tää alleviivaus tulee olla kaikessa klikattavissa, voisko sen alleviivauksen vaan heittää tonne yleiset.less -> .klikattava classin sisään? Saadaan sillä samantien kaikki, sekä tulevaisuudessa ei tarvi muistaa tota lisätä, tulee koodistakin vähän lyhyempää

2025-01-17 10:33 UTC, solita-staskila approved these changes
Jos vielä nuo nillitykset pushaat niin voi mergettää 👍

2025-01-17 10:33 UTC, solita-staskila commented on dev-resources/less/touch.less
> +.klikattava.alleviivaa {
Tän vois heittää tonne .klikattava sisälle: 

```css
.klikattava {
    cursor: pointer;

    &.alleviivaa {
      text-decoration: underline;
    }
}
```

2025-01-17 10:33 UTC, solita-staskila commented on dev-resources/less/touch.less
> +}
```suggestion
.klikattava {
    cursor: pointer;

    &.alleviivaa {
      text-decoration: underline;
    }
}
```

2025-01-17 10:33 UTC, solita-staskila commented on src/cljs/harja/views/urakkatilanne/kojelauta.cljs
>                        :on-click #(siirtymat/siirry-annettuun-valilehteen (:ely_id rivi) (:id rivi) {:taso1 :urakat
Nillitystä, mutta tässä on formatointi väärin, tabia jäänyt painamatta (vai mikä lienee teillä on formatointi näppäin)

2025-01-17 10:33 UTC, solita-staskila commented on src/cljs/harja/views/urakkatilanne/kojelauta.cljs
>                       :on-click #(siirtymat/siirry-annettuun-valilehteen (:ely_id rivi) (:id rivi) {:taso1 :urakat
Näissä kaikissa muissa sama

2025-01-17 12:48 UTC, merged

2025-01-17 13:41 UTC, solita-laurin commented on src/cljs/harja/views/urakkatilanne/kojelauta.cljs
>                        :on-click #(siirtymat/siirry-annettuun-valilehteen (:ely_id rivi) (:id rivi) {:taso1 :urakat
Kommentit resolvattu tiketissä 1264