HAR-5031-turvalaitteiden-geometriat
finnishtransportagency/harja pull request #779
Opened 2017-04-19 09:41 UTC by mikkoronkkomaki

2017-04-19 11:41 UTC, tatut requested changes

2017-04-19 11:41 UTC, tatut commented on src/clj/harja/palvelin/ajastetut_tehtavat/turvalaitteiden_geometriat.clj
> +  (jdbc/with-db-transaction [transaktio db]
Tässä tehdään transaktiossa IO:ta: haetaan HTTP:llä mahdollisesti hyvin pitkään kestävä resurssi.

Voisiko muuttaa siten, että ensin haetaan ja käsittelyssä vastan transaktio joka poistaa vanhat ja päivittää uudet sekä merkitsee suoritetuksi.

2017-04-20 09:14 UTC, mikkoronkkomaki commented on src/clj/harja/palvelin/ajastetut_tehtavat/turvalaitteiden_geometriat.clj
> +  (jdbc/with-db-transaction [transaktio db]
Joo ehdottomasti näin. Hyvä löydös.

2017-04-20 12:25 UTC, tatut approved these changes

2017-04-20 12:25 UTC, merged